### ISSUE TITLE
Add binary search.

### ISSUE THREAD

**Issue by jcads** [dscjntuc/Data-Structures-and-Algorithms#3]
Binary search is one of the fundamental searching algorithm when learning DS&A. I'd like to contribute and implement it in Java.

**Comment by manisaiprasad** [comment]
@jcads go ahead ✌🏻

**Comment by cBridges851** [comment]
Can I contribute by implementing binary search in C# please?

**Comment by manisaiprasad** [comment]
Sure you can @cBridges851

**Comment by xloli20** [comment]
Can I add it in C++?
