### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by manisaiprasad** [dscjntuc/Data-Structures-and-Algorithms#7]
Update Readme.md according to the programs in the repository

**Comment by charchitmangal** [comment]
Hello! pls assign it to me

**Comment by aaishikasb** [comment]
Hello, if the issue is still open, I would like to work on it.

**Comment by manisaiprasad** [comment]
@charchithere @aaishikasb There is a lot 
You can do at Readme, So show your creativity

**Comment by gaurang7goel** [comment]
Hi, is the issue still open , if yes then I am ready to contribute in it.
